version: "3.7"

services:
  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./web:/app"
    environment:
      - "REACT_APP_APOLLO_HTTP_URI=http://localhost:8000/graphql"
      - "REACT_APP_APOLLO_WS_URI=ws://localhost:8000/graphql"
      - "REACT_APP_APOLLO_SERVER_BASE_URL=http://localhost:8000"

  server-graphql:
    build:
      context: server-graphql
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - "./server-graphql:/app"
      - "/app/node_modules"
    environment:
      - "APP_PORT=8000"
      - "MONGO_HOST=mongodb"
      - "MONGO_PORT=27017"
      - "MONGO_USERNAME=root"
      - "MONGO_PASSWORD=root_password"
      - "MONGO_DATABASE=admin"
      - "INTERNAL_RABBIT_HOSTNAME=rabbitmq"
      - "INTERNAL_RABBIT_PORT=5672"
      - "INTERNAL_RABBIT_USERNAME=guest"
      - "INTERNAL_RABBIT_PASSWORD=guest"

  # server-rest:
  #   build:
  #     context: server-rest
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - "./server-rest:/app"
  #     - "/app/node_modules"

  # worker:
  #   build:
  #     context: worker
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - "./worker:/app"

  # rabbit:
  #   image: "rabbitmq:3-management"
  #   ports:
  #     - "15678:15672"
  #   volumes:
  #     - "rabbit-data:/var/lib/rabbitmq"
  #   environment:
  #     - "RABBITMQ_ERLANG_COOKIE=H1hK3rDP1qySM7UH"
  #     - "RABBITMQ_DEFAULT_USER=guest"
  #     - "RABBITMQ_DEFAULT_PASS=guest"
  #     - "RABBITMQ_DEFAULT_VHOST=/"
  #   hostname: rabbitmq

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=root_password"
      - "MONGO_INITDB_DATABASE=admin"

volumes:
  mongo-data:
  rabbit-data:
