version: "3"

services:
  traefik:
    image: traefik:1.7
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik:/etc/traefik/"

  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./web:/app"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:web.docker.localhost"
      - "traefik.port=3000"

  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./server:/app"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:server.docker.localhost"
      - "traefik.port=8000"
