version: "3"

services:
  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./wev:/app"
  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - "/app/node_modules"
      - "./server:/app"
