version: "3.5"

services:
  traefik:
    image: traefik:1.7
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
    deploy:
      replicas: 1
    networks:
      - verse
  
  web:
    image: daongocthanh/web
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.frontend.rule=Host:104.199.129.145"
        - "traefik.docker.network=demo_verse"
    environment:
      - "REACT_APP_APOLLO_HTTP_URI=http://104.199.129.145/server/graphql"
      - "REACT_APP_APOLLO_WS_URI=ws://104.199.129.145/server/graphql"
    networks:
      - verse

  server-graphql:
    image: daongocthanh/server-graphql
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=8000"
        - "traefik.frontend.rule=Host:104.199.129.145;PathPrefixStrip:/server"
        - "traefik.docker.network=demo_verse"
    environment:
      - "APP_PORT=8000"
      - "MONGO_HOST=mongodb"
      - "MONGO_PORT=27017"
      - "MONGO_USERNAME=root"
      - "MONGO_PASSWORD=root_password"
      - "MONGO_DATABASE=admin"
      - "INTERNAL_RABBIT_HOSTNAME=rabbitmq"
      - "INTERNAL_RABBIT_PORT=5672"
      - "INTERNAL_RABBIT_USERNAME=guest"
      - "INTERNAL_RABBIT_PASSWORD=guest"
    networks:
      - verse
    
  # worker:
  #   image: daongocthanh/demo-worker
  #   networks:
  #     - verse
  #   deploy:
  #     replicas: 1
  
  # rabbit:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "15678:15672"
  #   networks:
  #     - verse
  #   volumes:
  #     - "rabbit-data:/var/lib/rabbitmq"
  #   environment:
  #     - "RABBITMQ_ERLANG_COOKIE=H1hK3rDP1qySM7UH"
  #     - "RABBITMQ_DEFAULT_USER=guest"
  #     - "RABBITMQ_DEFAULT_PASS=guest"
  #     - "RABBITMQ_DEFAULT_VHOST:/"
  #   hostname: rabbitmq

  mongodb:
    image: mongo
    deploy:
      replicas: 1
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_username"
      - "MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password"
      - "MONGO_INITDB_DATABASE=admin"
    secrets:
      - "mongo_username"
      - "mongo_password"
    volumes:
      - "mongo-data:/data/db"
    networks:
      - verse

secrets:
  rabbit_username:
    file: secrets/rabbit_username.txt
  rabbit_password:
    file: secrets/rabbit_password.txt
  mongo_username:
    file: secrets/mongo_username.txt
  mongo_password:
    file: secrets/mongo_password.txt

volumes:
  mongo-data:
  rabbit-data:

networks:
  verse:
    driver: overlay
