version: "3"

services:
  traefik:
    image: traefik:1.7-alpine
    deploy:
      replicas: 1
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik:/etc/traefik/"
    networks:
      - "verse"

  mongodb:
    image: mongo
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=root_pw"
      - "MONGO_INITDB_DATABASE=demo"
    volumes:
      - "mongo-data:/data/db"
    networks:
      - "verse"

  web:
    image: daongocthanh/demo-web:1.0.3
    build: web
    deploy:
      replicas: 1
    networks:
      - "verse"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:web.docker.localhost"
      - "traefik.port=3000"

  server:
    image: daongocthanh/demo-server:1.0.4
    build: server
    deploy:
      replicas: 1
    networks:
      - "verse"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:server.docker.localhost"
      - "traefik.port=8000"

  worker:
    image: daongocthanh/demo-worker:1.0.4
    build: worker
    deploy:
      replicas: 3
    networks:
      - "verse"

volumes:
  mongo-data:

networks:
  verse:
    driver: overlay
