version: "3"

services:
  traefik:
    image: traefik:1.7
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik:/etc/traefik/"

  web:
    build: web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:awesome-domain.tk"
      - "traefik.port=3000"

  server:
    build: server
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:awesome-domain.tk;PathPrefixStrip:/server"
      - "traefik.port=8000"
