version: "3.5"

services:
  traefik:
    image: traefik:1.7
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
    deploy:
      replicas: 1
    networks:
      - demo_global
  
networks:
  demo_global:
    external: true
