version: "3"

services:
  traefik:
    image: traefik:alpine
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik:/etc/traefik"

  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./web:/app"
  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - "/app/node_modules"
      - "./server:/app"
