version: "3"

services:
  viz:
    image: bretfisher/visualizer
    ports:
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1

  # traefik:
  #   image: traefik:1.7-alpine
  #   deploy:
  #     replicas: 1
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #     - "443:443"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #     - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
  #   networks:
  #     - "verse"

  # rabbit:
  #   image: "rabbitmq:3-management"
  #   hostname: "rabbitmq"
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: "H1hK3rDP1qySM7UH"
  #     RABBITMQ_DEFAULT_USER: "guest"
  #     RABBITMQ_DEFAULT_PASS: "guest"
  #     RABBITMQ_DEFAULT_VHOST: "/"
  #   ports:
  #     - "15678:15672"
  #   networks:
  #     - "verse"

  mongodb:
    image: mongo
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=root_password"
      - "MONGO_INITDB_DATABASE=admin"
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"
    networks:
      - "verse"

  # web:
  #   image: daongocthanh/demo-web
  #   build: web
  #   ports:
  #     - "3000:3000"
  #   deploy:
  #     replicas: 1
  #     labels:
  #       - "traefik.enable=true"
  #       - "traefik.frontend.rule=Host:web.awesome-domain.tk"
  #       - "traefik.port=3000"
  #   networks:
  #     - "verse"

  # server-graphql:
  #   image: daongocthanh/demo-server-graphql
  #   ports:
  #     - "8000:8000"
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #     labels:
  #       - "traefik.enable=true"
  #       - "traefik.frontend.rule=Host:server.awesome-domain.tk"
  #       - "traefik.port=8000"
  #   networks:
  #     - "verse"

  server-rest:
    image: daongocthanh/demo-server-rest
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.port=8000"
    networks:
      - "verse"

  # worker:
  #   image: daongocthanh/demo-worker
  #   build: worker
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - "verse"

volumes:
  mongo-data:

networks:
  verse:
    driver: overlay
