version: "3.7"

services:
<<<<<<< HEAD
  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./web:/app"
    environment:
      - "REACT_APP_APOLLO_HTTP_URI=http://localhost:8000/graphql"
      - "REACT_APP_APOLLO_WS_URI=ws://localhost:8000/graphql"
      - "REACT_APP_APOLLO_SERVER_BASE_URL=http://localhost:8000"

  server:
    build:
      context: server-graphql
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - "./server-graphql:/app"
      - "/app/node_modules"
    environment:
      - "APP_PORT=8000"
      - "MONGO_HOST=mongodb"
      - "MONGO_PORT=27017"
      - "MONGO_USERNAME=root"
      - "MONGO_PASSWORD=root_password"
      - "MONGO_DATABASE=admin"
      - "INTERNAL_RABBIT_HOSTNAME=rabbitmq"
      - "INTERNAL_RABBIT_PORT=5672"
      - "INTERNAL_RABBIT_USERNAME=guest"
      - "INTERNAL_RABBIT_PASSWORD=guest"

=======
  # traefik:
  #   image: traefik:1.7-alpine
  #   ports:
  #     - "80:80"
  #     - "8086:8080"
  #     - "443:443"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #     - "./traefik/traefik.dev.toml:/etc/traefik/traefik.toml"
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "H1hK3rDP1qySM7UH"
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "15678:15672"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_username"
      - "MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password"
      - "MONGO_INITDB_DATABASE=admin"
    secrets:
      - "mongo_username"
      - "mongo_password"
    volumes:
      - "mongo-data:/data/db"

  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - "REACT_APP_APOLLO_HTTP_URI=http://localhost:8000/graphql"
      - "REACT_APP_APOLLO_WS_URI=ws://localhost:8000/graphql"
    volumes:
      - "./web:/app"

  server-graphql:
    build:
      context: server-graphql
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - "SERVER_PORT=8000"
      - "RABBIT_HOSTNAME=rabbit"
      - "RABBIT_PORT=5672"
      - "MONGO_HOST=mongodb"
      - "MONGO_PORT=27017"
      - "MONGO_DATABASE=admin"
    secrets:
      - "mongo_username"
      - "mongo_password"
      - "rabbit_username"
      - "rabbit_password"
    volumes:
      - "./server-graphql:/app"
      - "/app/node_modules"
>>>>>>> af68fc96af2345a890b402bc52bd770ffd370e71
  # server-rest:
  #   build:
  #     context: server-rest
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - "./server-rest:/app"
  #     - "/app/node_modules"

  # worker:
  #   build:
  #     context: worker
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - "./worker:/app"

  # rabbit:
  #   image: "rabbitmq:3-management"
  #   ports:
<<<<<<< HEAD
  #     - "15678:15672"
  #   volumes:
  #     - "rabbit-data:/var/lib/rabbitmq"
  #   environment:
  #     - "RABBITMQ_ERLANG_COOKIE=H1hK3rDP1qySM7UH"
  #     - "RABBITMQ_DEFAULT_USER=guest"
  #     - "RABBITMQ_DEFAULT_PASS=guest"
  #     - "RABBITMQ_DEFAULT_VHOST=/"
  #   hostname: rabbitmq

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=root_password"
      - "MONGO_INITDB_DATABASE=admin"
=======
  #     - "4000:4000"
  # worker:
  #   build:
  #     context: worker
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - "./worker:/app"
secrets:
  rabbit_username:
    file: secrets/rabbit_username.txt
  rabbit_password:
    file: secrets/rabbit_password.txt
  mongo_username:
    file: secrets/mongo_username.txt
  mongo_password:
    file: secrets/mongo_password.txt
>>>>>>> af68fc96af2345a890b402bc52bd770ffd370e71

volumes:
  mongo-data:
  rabbit-data:
