version: "3.5"

services:
  traefik:
    image: traefik:1.7-alpine
    ports:
      - "80:80"
      - "8086:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/traefik.dev.toml:/etc/traefik/traefik.toml"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=root_pw"
      - "MONGO_INITDB_DATABASE=demo"
    volumes:
      - "mongo-data:/data/db"

  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    volumes:
      - "./web:/app"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:web.docker.localhost"
      - "traefik.port=3000"

  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
    volumes:
      - "./server:/app"
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:server.docker.localhost"
      - "traefik.port=8000"

volumes:
  mongo-data:
