apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: web.docker.localhost
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: web-cluster-ip-service
              servicePort: 3000
    - host: server.docker.localhost
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 8000
