logLevel = "ERROR"

defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[api]

[docker]
domain = "awesome-domain.tk"
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false
