logLevel = "INFO"

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[api]

[docker]
domain = "docker.localhost"
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false
